DROP INDEX IF EXISTS "public"."Account_type_idx";
ALTER TABLE "public"."Account" RENAME COLUMN "type" TO "accountType";
ALTER TABLE "public"."Account" ADD COLUMN IF NOT EXISTS "normalBalance" TEXT NOT NULL DEFAULT 'DEBIT';
ALTER TABLE "public"."Account" ADD COLUMN IF NOT EXISTS "allowPosting" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "public"."Account" ADD COLUMN IF NOT EXISTS "isSystem" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "public"."Account" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "public"."Account" ALTER COLUMN "currency" SET DEFAULT 'USD';
CREATE INDEX IF NOT EXISTS "Account_accountType_idx" ON "public"."Account"("accountType");
DROP TABLE IF EXISTS "public"."Company" CASCADE;

CREATE TABLE "public"."CompanyProfile" ("id" INTEGER NOT NULL DEFAULT 1,"name" TEXT NOT NULL,"legalName" TEXT,"registrationNumber" TEXT,"taxNumber" TEXT,"country" TEXT NOT NULL DEFAULT 'United States',"city" TEXT,"address" TEXT,"baseCurrency" TEXT NOT NULL DEFAULT 'USD',"fiscalYearStartMonth" INTEGER NOT NULL DEFAULT 1,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "CompanyProfile_pkey" PRIMARY KEY ("id"));
CREATE TABLE "public"."Branch" ("id" SERIAL NOT NULL,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"city" TEXT,"airportCode" TEXT,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Branch_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Branch_code_key" ON "public"."Branch"("code");
CREATE TABLE "public"."FiscalYear" ("id" SERIAL NOT NULL,"name" TEXT NOT NULL,"startDate" TIMESTAMP(3) NOT NULL,"endDate" TIMESTAMP(3) NOT NULL,"status" TEXT NOT NULL DEFAULT 'OPEN',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "FiscalYear_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "FiscalYear_name_key" ON "public"."FiscalYear"("name");
CREATE TABLE "public"."AccountingPeriod" ("id" SERIAL NOT NULL,"fiscalYearId" INTEGER NOT NULL,"name" TEXT NOT NULL,"startDate" TIMESTAMP(3) NOT NULL,"endDate" TIMESTAMP(3) NOT NULL,"status" TEXT NOT NULL DEFAULT 'OPEN',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "AccountingPeriod_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "AccountingPeriod_fiscalYearId_name_key" ON "public"."AccountingPeriod"("fiscalYearId", "name");
CREATE INDEX "AccountingPeriod_status_idx" ON "public"."AccountingPeriod"("status");
ALTER TABLE "public"."AccountingPeriod" ADD CONSTRAINT "AccountingPeriod_fiscalYearId_fkey" FOREIGN KEY ("fiscalYearId") REFERENCES "public"."FiscalYear"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "public"."Currency" ("id" SERIAL NOT NULL,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"symbol" TEXT,"isBase" BOOLEAN NOT NULL DEFAULT false,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Currency_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Currency_code_key" ON "public"."Currency"("code");
CREATE TABLE "public"."ExchangeRate" ("id" SERIAL NOT NULL,"currencyId" INTEGER NOT NULL,"rate" DECIMAL(18,6) NOT NULL,"effectiveDate" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ExchangeRate_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ExchangeRate_currencyId_effectiveDate_key" ON "public"."ExchangeRate"("currencyId", "effectiveDate");
ALTER TABLE "public"."ExchangeRate" ADD CONSTRAINT "ExchangeRate_currencyId_fkey" FOREIGN KEY ("currencyId") REFERENCES "public"."Currency"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "public"."NumberSeries" ("id" SERIAL NOT NULL,"module" TEXT NOT NULL,"prefix" TEXT NOT NULL,"nextNumber" INTEGER NOT NULL DEFAULT 1,"padding" INTEGER NOT NULL DEFAULT 5,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "NumberSeries_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "NumberSeries_module_prefix_key" ON "public"."NumberSeries"("module", "prefix");
CREATE TABLE "public"."Role" ("id" SERIAL NOT NULL,"name" TEXT NOT NULL,"description" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Role_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Role_name_key" ON "public"."Role"("name");
CREATE TABLE "public"."Permission" ("id" SERIAL NOT NULL,"key" TEXT NOT NULL,"label" TEXT NOT NULL,"module" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Permission_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Permission_key_key" ON "public"."Permission"("key");
CREATE TABLE "public"."RolePermission" ("roleId" INTEGER NOT NULL,"permissionId" INTEGER NOT NULL,CONSTRAINT "RolePermission_pkey" PRIMARY KEY ("roleId", "permissionId"));
ALTER TABLE "public"."RolePermission" ADD CONSTRAINT "RolePermission_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "public"."Role"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "public"."RolePermission" ADD CONSTRAINT "RolePermission_permissionId_fkey" FOREIGN KEY ("permissionId") REFERENCES "public"."Permission"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "public"."User" ("id" SERIAL NOT NULL,"name" TEXT NOT NULL,"email" TEXT NOT NULL,"roleId" INTEGER,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "public"."User"("email");
ALTER TABLE "public"."User" ADD CONSTRAINT "User_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "public"."Role"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE "public"."SystemSetting" ("id" SERIAL NOT NULL,"key" TEXT NOT NULL,"value" TEXT NOT NULL,"group" TEXT NOT NULL DEFAULT 'SYSTEM',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "SystemSetting_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "SystemSetting_key_key" ON "public"."SystemSetting"("key");
CREATE TABLE "public"."JournalEntry" ("id" SERIAL NOT NULL,"entryNumber" TEXT NOT NULL,"entryDate" TIMESTAMP(3) NOT NULL,"description" TEXT,"status" TEXT NOT NULL DEFAULT 'DRAFT',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "JournalEntry_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "JournalEntry_entryNumber_key" ON "public"."JournalEntry"("entryNumber");
CREATE INDEX "JournalEntry_entryDate_idx" ON "public"."JournalEntry"("entryDate");
CREATE INDEX "JournalEntry_status_idx" ON "public"."JournalEntry"("status");
CREATE TABLE "public"."JournalLine" ("id" SERIAL NOT NULL,"journalEntryId" INTEGER NOT NULL,"accountId" INTEGER NOT NULL,"description" TEXT,"debit" DECIMAL(18,2) NOT NULL DEFAULT 0,"credit" DECIMAL(18,2) NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "JournalLine_pkey" PRIMARY KEY ("id"));
CREATE INDEX "JournalLine_accountId_idx" ON "public"."JournalLine"("accountId");
ALTER TABLE "public"."JournalLine" ADD CONSTRAINT "JournalLine_journalEntryId_fkey" FOREIGN KEY ("journalEntryId") REFERENCES "public"."JournalEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "public"."JournalLine" ADD CONSTRAINT "JournalLine_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "public"."Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
